name: omnirelay

services:
  omnirelay:
    image: ghcr.io/nergis0318/omnirelay:latest
    container_name: omnirelay
    env_file:
      - .env
    volumes:
      - omnirelay-data:/app/data
    ports:
      - "80:80"
    restart: unless-stopped
    dns: 1.1.1.1

volumes:
  omnirelay-data:
